apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-injector
  namespace: proxy-injector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy-injector
  template:
    metadata:
      labels:
        app: proxy-injector
    spec:
      serviceAccountName: proxy-injector
      containers:
        - name: proxy-injector
          image: quay.io/rdiazgav/proxy-injector:latest
          ports:
            - containerPort: 8443
          envFrom:
            - configMapRef:
                name: proxy-injector-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: proxy-injector-tls