apiVersion: v1
kind: Service
metadata:
  name: proxy-injector
  namespace: proxy-injector
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: proxy-injector-tls
spec:
  selector:
    app: proxy-injector
  ports:
    - port: 443
      targetPort: 8443